version: "2.1"

services:
    db:
        image: mysql:5.7
        container_name: db
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always
        networks:
          - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "8084:80"
        depends_on:
            - db
        networks:
          - default
    go-app:
        build: .
        container_name: go-app
        ports:
            - "8082:8082"
        depends_on:
            - db
        networks:
          - default
        volumes:
            - ./uploads:/app/uploads
networks:
  default: